
dependencies {
    implementation project(':base:jpa')
    implementation project(':base:dag')
    implementation project(':base:mongodb')
    implementation project(':base:elasticsearch')
    implementation project(':base:redis')
    implementation project(':web:core')
    testImplementation project(':web:test')

    // Trino 查询引擎 JDBC 客户端
    implementation group: 'io.trino', name: 'trino-jdbc', version: '483'

    // SQL解析器
    implementation group: 'com.github.jsqlparser', name: 'jsqlparser', version: '5.3'

    // Apache POI (Excel)
    implementation group: 'org.apache.poi', name: 'poi-ooxml', version: '5.4.0'

    implementation group: 'org.postgresql', name: 'postgresql', version: postgresqlVersion
}
