spring:
  application:
    name: fs-lm-service
  profiles:
    active: dev,idev
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.fs.web.lm.dsconfig.NamingStrategy
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
fs:
  lm:
    uploadPath: ./data/lm/
