spring:
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    quartz:
      url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf-8
      jdbc-url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf-8
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
