fs:
  format:
    date: yyyy-MM-dd HH:mm:ss

rpc:
  member:
    name: app-member-service
    rest: http://127.0.0.1:7801
  analyse:
    name: app-analyse-service
    rest: http://127.0.0.1:7802
  flink:
    name: app-flink-service
    rest: http://127.0.0.1:7803
  quartz:
    name: app-quartz-service
    rest: http://127.0.0.1:7804
  xlab:
    name: app-xlab-service
    rest: http://127.0.0.1:7805

feign:
  hystrix:
    enabled: true # Enable Fallback

spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    quartz:
      url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
    member:
      table-prefix: fs_member_
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      quartz:
