/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
