
dependencies {
    implementation project(':web:core')
    implementation project(':base:jpa')
    implementation project(':base:elasticsearch')
    implementation group: 'org.springframework.ai', name: 'spring-ai-starter-mcp-server-webmvc', version: '1.1.8'
    implementation("org.apache.poi:poi:5.5.1")
    implementation("org.apache.poi:poi-ooxml:5.5.1")
    implementation("org.apache.poi:poi-scratchpad:5.5.1") // 旧版 doc/xls/ppt (OLE2)
    implementation("org.apache.pdfbox:pdfbox:2.0.36") // PDF
}
