server:
  port: 8033
  servlet:
    session:
      timeout: 1800
      cookie:
        max-age: 2592000

spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.fs.base.jpa.mvc.PhysicalNamingStrategy
  thymeleaf:
    mode: HTML
    suffix: .html
    cache: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8
    username: root
    password: admin888
    table-prefix: test_
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

rpc:
  ucenter:
    rest: http://member.iisquare.com
    debug: 1 # 指定调试用户主键
